# ros configuration file

/**:
  ros__parameters:
    odometry_topic: "odometry"
    pose_topic: "none"
    detections_topic: "processed_gate_poses_array"
    corrected_localization_topic: "slam/corrected_localization"
    map_frame: "drone0/map"
    odom_frame: "drone0/odom"
    robot_frame: "drone0/base_link"
    viz_main_markers_topic: "slam_viz/markers/main"
    viz_temp_markers_topic: "slam_viz/markers/temp"
    main_graph_odometry_distance_threshold: 2.0
    main_graph_odometry_orientation_threshold: 1.0
    temp_graph_odometry_distance_threshold: 0.2
    temp_graph_odometry_orientation_threshold: 1.0
    odometry_is_relative: False
    generate_odom_map_transform: True
    # fixed_objects:
    #   gate_1:
    #     type: "aruco"
    #     pose: [4.0, 1.3, 1.13, 3.14] 
    #   gate_2:
    #     type: "aruco"
    #     pose: [4.0, -1.34, 1.16, 0.0]
    #   gate_3:
    #     type: "aruco"
    #     pose: [-4.0, -1.29, 1.16, 0.0]
    #   gate_4:
    #     type: "aruco"
    #     pose: [-3.97, 1.28, 1.17, 3.14]

